server:
  port: 8082
  servlet:
    context-path: /movies

spring:
  application:
    name: ms-movies

  datasource:
    url: jdbc:mysql://localhost:3306/MexFlix
    username: springuser
    password: springpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
